<?php
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
?>
<ul class="resource-list">
    <?php foreach ($items as $item): ?>
    <?php
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $this->translate('[Untitled]')]) : $item->displayTitle();
    $body = $bodyTerm ? $item->value($bodyTerm) : $item->displayDescription();
    $resourceTemplate = $item->resourceTemplate();
    $itemClass = [
        'OTG Person Record' => 'person',
        'OTG Event Record' => 'event',
        'OTG Single Class Event Record' => 'event'
    ];
    ?>
        <?php if (isset($resourceTemplate) && ($resourceTemplate->label() == 'OTG Person Record')): ?>
            <?php $resourceTemplateLabel = $resourceTemplate->label(); ?>
            <li class="item resource <?php echo $itemClass[$resourceTemplateLabel]; ?>">
                <div class="person-header">
                    <?php $sexValue = strtolower($item->value('otgevents:sex')); ?>
                    <?php echo $item->linkPretty('square', $heading); ?>
                    <span class="sex <?php echo $sexValue; ?>" title="<?php echo $sexValue; ?>" aria-label="<?php echo $sexValue; ?>"></span>
                </div>
                <div class="life-row">
                    <?php
                        $birthDate = $item->value('otgevents:birthDate');
                        $deathDate = $item->value('otgevents:deathDate');
                    ?>
                    <span class="birth date">Birth: <?php echo (isset($birthDate)) ? $birthDate : '-'; ?></span>
                    <span class="death date">Death: <?php echo (isset($deathDate)) ? $deathDate : '-'; ?></span>
                </div>
                <div class="description"><?php echo $this->escapeHtml($body); ?></div>
        <?php else: ?>
            <li class="item resource">
                <?php echo $item->linkPretty('square', $heading); ?>
                <?php if ($body): ?>
                <div class="description"><?php echo $this->escapeHtml($body); ?></div>
                <?php endif; ?>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
