<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/site/page.css', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('js/faceted-browse.js', 'FacetedBrowse'));
$this->headScript()->appendFile($this->assetUrl('js/site/page.js', 'FacetedBrowse'));
$this->facetedBrowse()->prepareFacets();
$nav = $this->currentSite()->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);


$this->htmlElement('body')->appendAttribute('class', 'faceted-browse-page visualizations resource browse');
$this->pageTitle($page->title(), 3);

$categories = $page->categories();
$categoryId = null;
$categoryQuery = null;
if (1 === count($categories)) {
    $category = current($categories);
    $categoryId = $category->id();
    $categoryQuery = $category->query();
}
?>
<div class="page-title"><h2>Visualizations</h2></div>
<div class="subhead">
    <div class="assets hero yellow default"> </div>
    <?php if ($activePage && (!$activePage['page']->hasPages())): ?>
        <?php echo $nav->menu()->setUlClass('horizontal menu sub-nav')->renderSubMenu(); ?>
    <?php endif; ?>
</div>
<ul class="horizontal menu view">
    <li><a href="#">Default</a></li>
    <li><a href="#">Table</a></li>
</ul>
<div id="container" 
    data-url-categories="<?php echo $this->escapeHtml($this->url(null, ['action' => 'categories'], true)); ?>"
    data-url-facets="<?php echo $this->escapeHtml($this->url(null, ['action' => 'facets'], true)); ?>"
    data-url-browse="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>"
    data-category-id="<?php echo $this->escapeHtml($categoryId); ?>"
    data-category-query="<?php echo $this->escapeHtml($categoryQuery); ?>">
    <div id="section-sidebar"></div>
    <div id="section-content"></div>
</div>
